In [1]:
import cv2

In [2]:
import numpy as np

In [3]:
ARUCO_DICT = {
	"DICT_4X4_50": cv2.aruco.DICT_4X4_50,
	"DICT_4X4_100": cv2.aruco.DICT_4X4_100,
	"DICT_4X4_250": cv2.aruco.DICT_4X4_250,
	"DICT_4X4_1000": cv2.aruco.DICT_4X4_1000,
	"DICT_5X5_50": cv2.aruco.DICT_5X5_50,
	"DICT_5X5_100": cv2.aruco.DICT_5X5_100,
	"DICT_5X5_250": cv2.aruco.DICT_5X5_250,
	"DICT_5X5_1000": cv2.aruco.DICT_5X5_1000,
	"DICT_6X6_50": cv2.aruco.DICT_6X6_50,
	"DICT_6X6_100": cv2.aruco.DICT_6X6_100,
	"DICT_6X6_250": cv2.aruco.DICT_6X6_250,
	"DICT_6X6_1000": cv2.aruco.DICT_6X6_1000,
	"DICT_7X7_50": cv2.aruco.DICT_7X7_50,
	"DICT_7X7_100": cv2.aruco.DICT_7X7_100,
	"DICT_7X7_250": cv2.aruco.DICT_7X7_250,
	"DICT_7X7_1000": cv2.aruco.DICT_7X7_1000,
	"DICT_ARUCO_ORIGINAL": cv2.aruco.DICT_ARUCO_ORIGINAL,
	"DICT_APRILTAG_16h5": cv2.aruco.DICT_APRILTAG_16h5,
	"DICT_APRILTAG_25h9": cv2.aruco.DICT_APRILTAG_25h9,
	"DICT_APRILTAG_36h10": cv2.aruco.DICT_APRILTAG_36h10,
	"DICT_APRILTAG_36h11": cv2.aruco.DICT_APRILTAG_36h11
}

In [4]:
arucoDict = cv2.aruco.Dictionary_get(ARUCO_DICT["DICT_4X4_50"])

In [22]:
tag = np.zeros((300, 300), dtype="uint8")

In [24]:
cv2.aruco.drawMarker(arucoDict, 0, 300, tag, 1)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [25]:
cv2.imshow("aruco_tag", tag)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
cv2.imwrite("aruco_tag_4x4_50_0.jpg", tag)

True

In [5]:
import imutils

In [29]:
aruco_img = cv2.imread("aruco_markers_4x4_1000.jpg")
aruco_img = imutils.resize(aruco_img, 600)
cv2.imshow("aruco_tag", aruco_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
aruco_params = cv2.aruco.DetectorParameters_create()
(corners, ids , rejected) = cv2.aruco.detectMarkers(aruco_img, arucoDict, parameters=aruco_params)

In [30]:
ids

array([2, 1, 3, 0], dtype=int32)

In [31]:
rejected

[array([[[515., 361.],
         [545., 360.],
         [546., 390.],
         [516., 391.]]], dtype=float32),
 array([[[426., 361.],
         [486., 360.],
         [487., 390.],
         [428., 391.]]], dtype=float32),
 array([[[146., 358.],
         [176., 357.],
         [177., 387.],
         [147., 388.]]], dtype=float32),
 array([[[505.,  46.],
         [551.,  48.],
         [548., 122.],
         [505., 121.]]], dtype=float32),
 array([[[ 87.,  53.],
         [117.,  51.],
         [118.,  81.],
         [ 88.,  82.]]], dtype=float32)]

In [6]:
def detectMarkers(aruco_img, arucoDict):
    
    aruco_params = cv2.aruco.DetectorParameters_create()
    (corners, ids , rejected) = cv2.aruco.detectMarkers(aruco_img, arucoDict, parameters=aruco_params)
    if len(corners)>0:
        ids = ids.flatten()

        for (marker_corner, marker_id) in zip(corners, ids):
            marker_corner = marker_corner.reshape((4,2))      
            (topLeft, topRight, bottomRight, bottomLeft) = marker_corner
            topRight = (int(topRight[0]), int(topRight[1]))
            bottomRight = (int(bottomRight[0]), int(bottomRight[1]))
            bottomLeft = (int(bottomLeft[0]), int(bottomLeft[1]))
            topLeft = (int(topLeft[0]), int(topLeft[1]))

            cv2.line(aruco_img, topLeft, topRight, (0, 255, 0), 2)
            cv2.line(aruco_img, topRight, bottomRight, (0, 255, 0), 2)
            cv2.line(aruco_img, bottomRight, bottomLeft, (0, 255, 0), 2)
            cv2.line(aruco_img, bottomLeft, topLeft, (0, 255, 0), 2)

            cX = int((topLeft[0] + bottomRight[0]) / 2.0)
            cY = int((topLeft[1] + bottomRight[1]) / 2.0)
            cv2.circle(aruco_img, (cX, cY), 4, (0, 0, 255), -1)

            cv2.putText(aruco_img, str(marker_id),
            (topLeft[0], topLeft[1] - 5), cv2.FONT_HERSHEY_SIMPLEX,
            0.5, (0, 255, 0), 2)
            print("[INFO] ArUco marker ID: {}".format(marker_id))
        
        
            return aruco_img

In [7]:
cv2.imshow("aruco_tag", aruco_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'aruco_img' is not defined

In [8]:
import sys

In [13]:
capture = cv2.VideoCapture(2)

In [ ]:
while True:
    ret, frame = capture.read()
#if not ret:
#    sys.exit('Reads the next frame failed')
#    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    #aruco_img = detectMarkers(frame, arucoDict)
    cv2.imshow("azure_kinect", frame)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [12]:
ret

False